
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 25 16:54:37 BOT 2019
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Variable = 4;
  public static final int Multiplicacion = 13;
  public static final int Division = 14;
  public static final int Cadena = 7;
  public static final int ERROR = 6;
  public static final int DeclararE = 8;
  public static final int EOF = 0;
  public static final int Linea = 2;
  public static final int Suma = 11;
  public static final int error = 1;
  public static final int Decir = 10;
  public static final int Igual = 3;
  public static final int Numero = 5;
  public static final int Resta = 12;
  public static final int DeclararP = 9;
}

